const $=id=>document.getElementById(id);const fields=['venue','item','date','time','site','watch','sound','firstAvailable'];
async function worker(message){const reply=await chrome.runtime.sendMessage(message);if(!reply?.ok)throw Error(reply?.error||'后台未确认操作，请重试');return reply;}
function prefs(){const p={};for(const k of fields)p[k]=$(k).type==='checkbox'?$(k).checked:$(k).value.trim();return VenueCore.validate(p)}
async function platform(){const tabs=await chrome.tabs.query({active:true,currentWindow:true});const t=tabs[0];if(!t?.url?.startsWith('https://sports.sjtu.edu.cn/pc/'))throw Error('请先切到体育场馆平台标签页，再打开本扩展');return t;}
async function send(type,p){const tab=await platform();try{const r=await chrome.tabs.sendMessage(tab.id,{type,preferences:p});if(!r?.ok)throw Error(r?.error||'页面无响应');return r.data;}catch(e){if(/Receiving end|establish connection/.test(e.message))throw Error('页面脚本尚未加载，请刷新平台页面后重试');throw e;}}
async function refresh(){const {preferences={},lastResult,status,logs=[]}=await chrome.storage.local.get(['preferences','lastResult','status','logs']);for(const k of fields)if(preferences[k]!==undefined){if($(k).type==='checkbox')$(k).checked=preferences[k];else $(k).value=preferences[k];}
 if(!$('date').value)$('date').value=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 $('result').replaceChildren();if(lastResult){const summary=document.createElement('p');summary.textContent=`${lastResult.venue} · ${lastResult.item}\n${lastResult.date} ${lastResult.start}–${lastResult.end}：${lastResult.count} 个可选场地`;$('result').append(summary);for(const s of lastResult.slots){const row=document.createElement('div');row.className=s.available?'available':'unavailable';row.textContent=s.site+' · '+(s.available?'页面显示可选':s.selected?'你已选中':'页面显示不可选');$('result').append(row);}const note=document.createElement('p');note.className='small';note.textContent='页面读取时间：'+new Date(lastResult.readAt).toLocaleString()+'；不代表服务器数据刷新时间。';$('result').append(note);}else $('result').textContent=status||'尚未读取';
 $('logs').replaceChildren();for(const log of logs.slice(0,12)){const el=document.createElement('div');el.className='entry';el.textContent=new Date(log.time).toLocaleString()+' · '+log.message;$('logs').append(el);}}
async function act(fn){for(const e of document.querySelectorAll('button'))e.disabled=true;try{await fn();}catch(e){$('message').textContent=e.message;}finally{for(const e of document.querySelectorAll('button'))e.disabled=false;}}
for(const id of ['save','apply'])$(id).onclick=()=>act(async()=>{const p=prefs();if(p.watch)p.watchTabId=(await platform()).id;await worker({type:'save',preferences:p});$('message').textContent='已保存';if(p.watch){try{await send('watchNow',p);}catch{}}await refresh()});
$('open').onclick=()=>act(async()=>{await worker({type:'open'});$('message').textContent='已打开平台，请手动登录并选择场馆'});
$('catalog').onclick=()=>act(async()=>{const data=await send('catalog');for(const [id,values] of [['venues',data.venues],['items',data.items]]){const list=$(id);list.replaceChildren();for(const v of [...new Set(values)]){const option=document.createElement('option');option.value=v;list.append(option);}}$('message').textContent='已读取当前页面可见选项，点击输入框查看建议'});
for(const type of ['prepare','read'])$(type).onclick=()=>act(async()=>{const p=prefs();if(p.watch)p.watchTabId=(await platform()).id;await worker({type:'save',preferences:p});const data=await send(type,p);await worker({type:'result',data});$('message').textContent='已读取并高亮。请在平台自行选择场地、核对金额并提交。';await refresh()});
for(const type of ['test','ack'])$(type).onclick=()=>act(async()=>{const reply=await worker({type});$('message').textContent=type==='test'?'已触发测试提醒':reply.audioStopped===false?'通知已清除，但声音停止失败；请查看日志':'声音和通知已停止';await refresh()});
$('export').onclick=async()=>{const {logs=[]}=await chrome.storage.local.get('logs');const url=URL.createObjectURL(new Blob([JSON.stringify(logs,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='venue-helper-log.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
refresh();
